spring.application.name=IdentityService
server.port=8080


# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/identityservice
spring.datasource.username=postgres
spring.datasource.password=lakshit
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pretty SQL formatting
spring.jpa.properties.hibernate.format_sql=true